name: IOM-Notice-Alert-Bot

on:
  workflow_dispatch: # Manually run the workflow
  push:
    branches: [ "master" ]
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run the code
      run: npm start
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    - name: Configure Git
      run: |
       git config --global user.email "rohityadav.se@gmail.com"
       git config --global user.name "Rohit Yadav"
    - name: Commit files
      run: |
        git add .
        git commit -m "Updated chatIds"
    - name: Push changes
      run: |
          git push origin HEAD:master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
