name: IOM-Notice-Alert-Bot

on:
  workflow_dispatch: # Manually run the workflow
  push:
    branches: ["master"]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run the bot
        run: npm start
        env:
          TELEGRAM_BOT_TOKEN_IOE: ${{ secrets.TELEGRAM_BOT_TOKEN_IOE }}
          TELEGRAM_BOT_TOKEN_IOM: ${{ secrets.TELEGRAM_BOT_TOKEN_IOM }}

      - name: Check for Changes
        run: |
          git add .
          if git diff --quiet HEAD; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Configure Git
        if: env.changes == 'true'
        run: |
          git config --global user.name "Rohit Yadav"
          git config --global user.email "rohityadav.se@gmail.com"

      - name: Commit Changes
        if: env.changes == 'true'
        run: |
          git commit -m "Auto-commit: Detected changes"

      - name: Push Changes
        if: env.changes == 'true'
        run: git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
